### ISSUE TITLE
Can not connect to Nexus switch with VDC - connection hangs

### ISSUE THREAD

**Issue by eoprede** [CiscoTestAutomation/unicon.plugins#29]
Here's the log:

```
2021-07-15 19:22:12,063: %UNICON-INFO: +++ initializing handle +++

2021-07-15 19:22:12,075: %UNICON-INFO: connection to 0055-router-7018-name-replaced
ssh -l username 10.192.255.23
Role changed to: netops-user/PRD_NETOPS
Z Access to this device or the attached
networks is prohibited without express written permission.
Violators will be prosecuted to the fullest extent of both civil
and criminal law.
ZPassword: 
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (c) 2002-2016, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under
license. Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or the GNU
Lesser General Public License (LGPL) Version 2.1. A copy of each
such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://www.opensource.org/licenses/lgpl-2.1.php

0055-router-7018-name-replaced# 

2021-07-15 19:22:16,162: %UNICON-INFO: We may be on a VDC, checking
show vdc


Switchwide mode is m1 f1 m1xl f2 m2xl f2e f3 

vdc_id  vdc_name                          state               mac                 type        lc      
------  --------                          -----               ----------          ---------   ------  
2       0055-router-7018-name-replaced          active              04:c5:a4:e8:37:c2   Ethernet    m1 m1xl m2xl 


0055-router-7018-name-replaced# 

2021-07-15 19:22:16,332: %UNICON-INFO: Current VDC 0055-router-7018-name-replaced

2021-07-15 19:22:16,333: %UNICON-INFO: +++ initializing handle +++



0055-router-7018-name-replaced# 

```

Exception:

```
Issue with the parser show interface

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 523, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 554, in genie.conf.base.device.Device._get_parser_output
TypeError: device is not connected, output must be provided.
```
Commenting out lines 49-56 in /unicon/plugins/nxos/connection_provider.py fixes the issue, so it has something to do with the renaming of the hostname.

**Comment by akhosrav** [comment]
Thanks for info, I will try to check the code

**Comment by akhosrav** [comment]
@eoprede 
I could not reproduce the error on pyATS version 21.6 would you please confirm which version you are using?

**Comment by eoprede** [comment]
@akhosrav Yes, using pyats==21.6 and genie==21.6
I think the issue is that my name has "-" sign in it and VDC has name identical to hostname.

**Comment by akhosrav** [comment]
Thanks for info, I will look to it.

**Comment by eoprede** [comment]
Some additional info that may help: the device is Nexus 7018 switch running 6.2.16  code
The SSH connection is made into the VDC directly, not the admin VDC.

**Comment by akhosrav** [comment]
@eoprede 
Thanks a lot, noted

**Comment by domachad** [comment]
Hi @eoprede,
Can you please update to version 21.7 and test it again?

This part of the code was modified, so it's important to test it again and verify if it works for you now, if the problem persists, or if any new issues arise.

Thanks in advance

**Comment by eoprede** [comment]
@domachad The issue is resolved, thank you!
